In [1]:
import tensorflow as tf

In [2]:
a=tf.constant(1)
b=tf.constant(2)
a+b

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
a.ndim

0

In [4]:
c=tf.constant([1,1])

In [5]:
c.ndim

1

In [6]:
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1])>

In [7]:
matrix=tf.constant([[2,3],[2,3]])

In [8]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [2, 3]])>

In [9]:
matrix.ndim

2

In [10]:
another_matrix=tf.constant([[10.,7.],[2.,3.]],dtype=tf.float16)

In [11]:
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 2.,  3.]], dtype=float16)>

In [12]:
changable=tf.Variable([10,7])
changable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [13]:
changable[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7])>

In [14]:
c[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
random_1=tf.random.Generator.from_seed(32)
random_1=random_1.normal(shape=(3,2))

In [16]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.7901182 ,  1.585549  ],
       [ 0.4356279 ,  0.23645182],
       [-0.1589871 ,  1.302304  ]], dtype=float32)>

In [17]:
random_2=tf.random.Generator.from_seed(32)
random_2=random_2.normal(shape=(3,2))
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [18]:
not_shuffled=tf.constant([[1,2],[3,4],[5,6]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]])>

In [19]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [20]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [21]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]])>

In [22]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [23]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [24]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [26]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [27]:
A.dtype

tf.int32

In [28]:
A.shape

TensorShape([2, 3, 4])

In [29]:
tf.size(A).numpy()

24

In [30]:
A[:1,:2]

<tf.Tensor: shape=(1, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])>

In [31]:
A[:1,:]

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])>

In [32]:
tf.expand_dims(A,axis=1)

<tf.Tensor: shape=(2, 1, 3, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]],


       [[[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]])>

In [2]:
tensor=tf.constant([[20,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 17],
       [13, 14]])>

In [3]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20,  7],
       [ 3,  4]])>

In [4]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200,  70],
       [ 30,  40]])>

In [5]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200,  70],
       [ 30,  40]])>

In [6]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[421, 168],
       [ 72,  37]])>

In [7]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400,  49],
       [  9,  16]])>

In [8]:
Y=tf.constant([[2,3],[3,4],[4,5]])

In [10]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4],
       [4, 5]])>

In [11]:
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 3],
       [4, 4, 5]])>

In [13]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5]])>

In [18]:
tf.tensordot(Y,tensor,axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[49, 26],
       [72, 37],
       [95, 48]])>

In [19]:
tf.matmul(Y,tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[49, 26],
       [72, 37],
       [95, 48]])>

In [23]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20,  3],
       [ 7,  4]])>

In [24]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20,  7],
       [ 3,  4]])>

In [25]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[421, 168],
       [ 72,  37]])>

In [26]:
tf.matmul(tf.transpose(tensor),tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[409, 152],
       [152,  65]])>

In [27]:
B=tf.constant([1.,2.])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [28]:
D=tf.cast(B,dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

In [29]:
D= tf.constant([-1,-2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2])>

In [30]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [31]:
import numpy as np

In [32]:
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([11, 54, 57, 84, 10,  5, 50, 76,  1, 21, 99, 78, 34, 57, 69, 14, 13,
       25, 76, 46, 91,  7, 52, 50,  8, 21, 95,  3, 13, 90, 59,  5, 87, 32,
       22, 86, 90, 28,  4, 43, 12, 66, 39, 72, 60, 43, 56, 27,  4, 87])>

In [33]:
tf.size(E)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [34]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [35]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [36]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=44>

In [37]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2232>

In [44]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.546856>

In [45]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=933.1104>

In [47]:
tf.random.set_seed(32)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.54520595, 0.13372338, 0.45232666, 0.15582252, 0.9621073 ,
       0.8151462 , 0.4068215 , 0.9565903 , 0.5532354 , 0.44936454,
       0.01469815, 0.86204493, 0.12014258, 0.91072273, 0.00848019,
       0.62772846, 0.8167286 , 0.98235905, 0.06410611, 0.17873585,
       0.07358396, 0.95524645, 0.5906956 , 0.3774085 , 0.9427308 ,
       0.32449841, 0.05033565, 0.6481848 , 0.97997856, 0.7848562 ,
       0.8223983 , 0.25406194, 0.21289039, 0.18566561, 0.18804717,
       0.5875702 , 0.45183384, 0.5508704 , 0.18366766, 0.55480397,
       0.72248566, 0.66862214, 0.46865964, 0.50943816, 0.61882794,
       0.5858562 , 0.7246859 , 0.88589907, 0.7049539 , 0.00409675],
      dtype=float32)>

In [48]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [49]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.98235905>

In [50]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.98235905>

In [51]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [52]:
G=tf.constant(tf.random.uniform(shape=[50]),shape=(5,10))
G

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.20274532, 0.0362395 , 0.45186257, 0.72931254, 0.59773815,
        0.6252638 , 0.58525324, 0.68096423, 0.32602644, 0.01932275],
       [0.22446549, 0.37494373, 0.73189723, 0.88004696, 0.7486503 ,
        0.37286603, 0.79102564, 0.23662508, 0.46818578, 0.21304202],
       [0.14157367, 0.09235609, 0.9034941 , 0.77694905, 0.57940197,
        0.60302424, 0.8027278 , 0.92220044, 0.90689754, 0.38798702],
       [0.37056744, 0.27422643, 0.6186545 , 0.9105128 , 0.42198884,
        0.7742996 , 0.4347055 , 0.19009268, 0.90281   , 0.35568738],
       [0.9403497 , 0.21564186, 0.94391954, 0.15408313, 0.04337871,
        0.10940921, 0.4930966 , 0.34173262, 0.16191673, 0.10891414]],
      dtype=float32)>

In [56]:
tf.squeeze(tf.reshape(G,shape=[1,1,50]))

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.20274532, 0.0362395 , 0.45186257, 0.72931254, 0.59773815,
       0.6252638 , 0.58525324, 0.68096423, 0.32602644, 0.01932275,
       0.22446549, 0.37494373, 0.73189723, 0.88004696, 0.7486503 ,
       0.37286603, 0.79102564, 0.23662508, 0.46818578, 0.21304202,
       0.14157367, 0.09235609, 0.9034941 , 0.77694905, 0.57940197,
       0.60302424, 0.8027278 , 0.92220044, 0.90689754, 0.38798702,
       0.37056744, 0.27422643, 0.6186545 , 0.9105128 , 0.42198884,
       0.7742996 , 0.4347055 , 0.19009268, 0.90281   , 0.35568738,
       0.9403497 , 0.21564186, 0.94391954, 0.15408313, 0.04337871,
       0.10940921, 0.4930966 , 0.34173262, 0.16191673, 0.10891414],
      dtype=float32)>

In [57]:
some_list=[0,1,2,3,4]

tf.one_hot(some_list,depth=len(some_list))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [58]:
tf.one_hot(some_list,depth=len(some_list),on_value='deep',off_value='python')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'deep', b'python', b'python', b'python', b'python'],
       [b'python', b'deep', b'python', b'python', b'python'],
       [b'python', b'python', b'deep', b'python', b'python'],
       [b'python', b'python', b'python', b'deep', b'python'],
       [b'python', b'python', b'python', b'python', b'deep']],
      dtype=object)>

In [59]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [61]:
b=tf.square(H)
b

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [62]:
tf.sqrt(tf.cast(b,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.9999999 , 2.9999998 , 3.9999998 , 5.        ,
       5.9999995 , 6.9999995 , 7.9999995 , 9.        ], dtype=float32)>

In [63]:
tf.sqrt([1.,4.,9.])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [64]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [65]:
J=tf.constant(np.array([1.,2.,3.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [71]:
np.array(J),type(np.array(J)),np.array(J).dtype

(array([1., 2., 3.]), numpy.ndarray, dtype('float64'))

In [72]:
J.numpy(),type(J.numpy())

(array([1., 2., 3.]), numpy.ndarray, tf.float64)

In [73]:
numpy_J=tf.constant(np.array([3.,4.,5.]))
tensor_J=tf.constant([3.,4.,5.])
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)